name = "JuliaVariables"
uuid = "b14d175d-62b4-44ba-8fb7-3064adc8c3ec"
authors = ["thautwarm"]
version = "0.2.4"

[deps]
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
NameResolution = "71a1bf82-56d0-4bbc-8a3c-48b961074391"

[compat]
MLStyle = "~0.4.2"
NameResolution = "~0.1.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
